### ISSUE TITLE
GooglePlusAPIError: Access Not Configured. Google+ API has not been used in project [id] before or it is disabled.

### ISSUE THREAD

**Issue by Armour** [googlesamples/google-photos#1]
Hi Team, I meet this error when I try to run the sample code and I have to enable Google+ API to run it. I think maybe we should add a notice about this in the README.md? 

![screen shot 2018-05-08 at 11 11 30](https://user-images.githubusercontent.com/5276065/39775103-b5c50e74-52b1-11e8-8ff9-bc4857d8f113.jpg)
![screen shot 2018-05-08 at 11 11 39](https://user-images.githubusercontent.com/5276065/39775102-b5ada91e-52b1-11e8-85ac-256d834a3222.jpg)

**Comment by ithinkihaveacat** [comment]
Just reporting this in case someone else discovers the same thing: after enabling the Google+ API via the link given in the error message as above, the Photos API seemed to get disabled--I had to re-enable that. I'm pretty sure I enabled it beforehand, but maybe I screwed up.

**Comment by jfschmakeit** [comment]
Thanks for the report and the workaround!

(I think there's a different scope the app should use that doesn't require the Google+ API to be enabled.)

**Comment by RochaRicardo** [comment]
Same error happen to me, but after follow the link the demo start working good :)

**Comment by springuper** [comment]
This is an exception thrown in `passport-google-oauth20`, you can add `userProfileURL: "https://www.googleapis.com/oauth2/v3/userinfo"` option to workaround, see details here: https://github.com/jaredhanson/passport-google-oauth2/issues/50

**Comment by jfschmakeit** [comment]
My apologies - I forgot to close this issue. This was already fixed in 3fbab5c808f8cdc40c31ac251256e15bd4286ecc a few weeks ago by setting the `userProfileURL` like you suggested.
