### ISSUE TITLE
Does it support image uploads? (REST API)

### ISSUE THREAD

**Issue by vusdo** [googlesamples/google-photos#13]
The document has an upload function.

It does not exist in the sample.

I want to know if the image upload function is a stable function.

Where is the article on response types for image upload failures?

**Comment by jfschmakeit** [comment]
Media uploads are supported, but unfortunately we haven't published a REST sample for it. You can find more details about the calls and the upload functionality in the developer guide here: https://developers.google.com/photos/library/guides/upload-media

(Also note that the sample code for the [Java](https://github.com/google/java-photoslibrary) and [PHP](https://github.com/google/php-photoslibrary) client libraries show uploading as well.)
