### ISSUE TITLE
Broken images in gallery

### ISSUE THREAD

**Issue by ithinkihaveacat** [googlesamples/google-photos#2]
The "Photo frame preview" shows many broken images:

<img width="1205" alt="screen shot 2018-05-09 at 8 08 18 am" src="https://user-images.githubusercontent.com/51244/39822865-8c9136b8-5360-11e8-933c-33a5feb1eef9.png">

Clicking on one of the broken image links shows an error "The requested content cannot be loaded":

<img width="1230" alt="screen shot 2018-05-09 at 8 08 31 am" src="https://user-images.githubusercontent.com/51244/39822900-a88631d4-5360-11e8-9aff-a6a4112b2843.png">

Clicking on the "Click to open in Google Photos" link at the bottom does open the photo on photos.google.com, as expected.

All of these photos were uploaded fairly recently (in the last 15 minutes?) if that makes any difference.

**Comment by jfschmakeit** [comment]
This is curious. Here are a few questions that might help us figure out what's going on here:

Do the same images work now after it has been a few days?
Can you view the photos on the Google Photos website? (https://photos.google.com/)
What format are the photos in? (Google Photos website -> navigate to photo -> info icon -> "photo" icon)
Have you changed anything in the code?

Could you also add a few expired base urls to this issue? That might help us track down if there's something going on from the API side. 
(Note - base URLs expire after ~60 minutes, before that they are accessible to anyone with the full URL. In this app you can get it from the image on the preview page: right click on an image -> copy link address. Try opening the URL in your browser to see if they are still accessible or if they have expired.

If this doesn't work, you can also get the base URL from the response returned by the API
Run the sample app in debug mode and get the image url from the response that's returned from the API: https://github.com/googlesamples/google-photos/blob/master/REST/PhotoFrame/README.md#troubleshooting 
You can then try opening the URL with a height/width parameter in a browser to see if they are still accessible or if they have expired: https://developers.google.com/photos/library/guides/access-media-items#image-base-urls

**Comment by ithinkihaveacat** [comment]
This works as expected now (maybe temporary glitch somewhere?), closing. Responses below, for posterity.

> Do the same images work now after it has been a few days?

Yes! They do.

I also tried uploading some new images and they appeared in the Photo Frame Sample as expected.

> Can you view the photos on the Google Photos website?

Yes.

> What format are the photos in?

JPG.

> Have you changed anything in the code?

No, just the `config.oAuth*` variables.

**Comment by masterhui** [comment]
The same happened (and is still ongoing) today to me. The same photo frame demo code work yesterday without problems. Today, it's broken. Is the Photos API down?

![image](https://user-images.githubusercontent.com/3931642/46972816-c52a1300-d0bf-11e8-9fc0-e72748169fa1.png)
