### ISSUE TITLE
This sample not compatible with the latest version of node.js v10.23.0

### ISSUE THREAD

**Issue by arunkaggarwal** [googlesamples/google-photos#23]
Dear Google developer community.
I have a humble request. I am trying to run this sample application under the latest version of Node.js. However I keep running into several compiler issues in app.js. For example I had to change the following lines to move forward

//import bodyParser from 'body-parser';
var bodyParser = require ('body-parser');

Now I am stuck at this line in app.js.
const dirname = path.dirname(new URL(import.meta.url).pathname);
                                            ^^^^
SyntaxError: Cannot use 'import.meta' outside a module

Would someone please help me in the migration of this great sample app to the latest version of node.js? I am not Node.js expert. I am sure someone with node.js expertise has already migrated it to the latest version of node.js. Would you kindly share it here for people like me?

Thanks in advance
-Arun

**Comment by arunkaggarwal** [comment]
Does anyone have a working version of this sample on Windows? Please share the zip file. I am stuck.

**Comment by jfschmakeit** [comment]
How are you running the app? If you are using an IDE, it may not be picking up the configuration in the `package.json` file. Have you tried running it directly from the commandline per the steps in the [README](https://github.com/googlesamples/google-photos/blob/main/REST/PhotoFrame/README.md#set-up), using the `npm` and `node` commands directly? 
Alternatively, it sounds like your environment isn't quite set up for JavaScript ES6. What version of Node JS are you using?
 

Regarding running the sample on Windows, it sounds like you might be running into issue #21 - see the suggested workaround there while we are working on updating this app.

**Comment by arunkaggarwal** [comment]
Thank you so much Jan-Felix for your reply. Please find answers below to your questions.
1) I am using node app.js from Node.js command prompt just like it is documented in README
2) I have tried 2 versions of Node.js 1) 10.23.0 (Latest) 2) 7.8.0 documented in the README.  I get errors on both. 
3) I did a npm install in both versions. Does that not setup JavaScript ES6 automatically? Is there a separate step to install JavaScript ES6. Please let me know
4) Issue #21 will help only when I can compile the solution successfully. I am stuck much before than that.

Any help will be deeply appreciated.
Regards and thanks in advance
-Arun

**Comment by jfschmakeit** [comment]
@arunkaggarwal Can you try the latest Node.js LTS release? (see https://nodejs.org/en/ - version `16.13.1 LTS` ) I have just been able to successfully run the application using this version on Windows. 

Also make sure that you have navigated into the `REST/PhotoFrame` before running `npm install` and then `node app.js`. 

We will update the README, the referenced version is quite old and may not work correctly with our latest changes.

**Comment by arunkaggarwal** [comment]
Thank you so much Jan-Felix for your reply. You are my hero for the day. I was able to run the solution after installing node.js ver 16.13.1 LTS. Hope it will be helpful to other potential developers who may try to run this on Windows.

**Comment by jfschmakeit** [comment]
That's great to hear! Glad you were able to get it working. We are going to update the README to specifically point developers towards the latest LTS version, that should hopefully help others in the future.
