### ISSUE TITLE
install

### ISSUE THREAD

**Issue by GerhardMes** [googlesamples/google-photos#3]
tryed to install the script going through the readme.
My first issue is with the line: "Set the authorized JavaScript origin to ..."  - where?
Having left this, but everything else - I get an error when running "node app.js"
  a) express-session deprecated undefined resave option
  b) express-session deprecated undefined saveUninitialized option
.....

Any advice for me? Thanks

**Comment by individual8** [comment]
Same here.

**Comment by individual8** [comment]
Would really like to play with and learn from it.

**Comment by jfschmakeit** [comment]
@GerhardMes - the "authorized JavaScript origin" refers to the credentials configuration in your Google Developers project. You need to enable the "Google Photos Library API" and set up "OAuth credentials" for a "Web Application. You can configure the URLs during the credentials creation. The guide in our developer documentation should walk you through it: https://developers.google.com/photos/library/guides/get-started#configure-your-project 
(I'll see if we can make the README a bit clearer.)


I haven't seen the other error message before, let me take a look and get back to you.
Is your npm installation uptodate? Which OS are you using? Did all packages get installed successfully from running `npm install` ?

**Comment by jfschmakeit** [comment]
> a) express-session deprecated undefined resave option
> b) express-session deprecated undefined saveUninitialized option

These warnings were caused by two missing parameters for the session middleware.
I have just added them in https://github.com/googlesamples/google-photos/commit/273493ec689d04c9995ef1c1d679d7b0e600cd04 and bumped the dependencies to the latest versions as well.
